import React, { Component } from "react";
import Helmet from "react-helmet";
import WebBase from "../components/WebBase";

class TermsOfServiceContainer extends Component {
    render() {
        return (
            <>
                <WebBase>
                    <div className="container-xl">
                        <div className="row">
                            <div className="col-xl-12" data-aos="fade-up" data-aos-duration="3000">
                                <div className="headingRow">
                                    <h1>Terms</h1>
                                </div>
                                <div className="textRow">
                                    <h2>Thanks for joining Procezo!</h2>
                                    <p>These Terms of Service along with any other terms and policies referenced herein, and are incorporated herein by reference and form an integral part hereof, as amended from time to time (these “Terms”) constitute a legally binding agreement as of the Effective Date (as defined below), governing your access to, and the use of www.procezo.com and any related website owned or operated by Procezo (the “Sites”), and the use of, and registration with, procezo.com Service (defined below) through the Sites, a mobile application or through any other means. These Terms are between Envigo Marketing Limited Ltd. (“Procezo”, “us”, “we” or “our”) and you, either individually, or on behalf of your employer or any other entity which you represent (“you” or “your”). In case you represent your employer or another entity, you hereby represent that (i) you have full legal authority to bind your employer or such entity (as applicable) to these Terms; and (ii) after reading and understanding these Terms, you agree to these Terms on behalf of your employer or the respective entity (as applicable), and these Terms shall bind your employer or such entity (as the case may be).</p>
                                    <p>PLEASE NOTE THAT YOU ARE DEEMED AS AN AUTHORIZED REPRESENTATIVE OF YOUR EMPLOYER OR AN ENTITY (AS APPLICABLE): (I) IF YOU ARE USING YOUR EMPLOYER OR AN ENTITY’S EMAIL ADDRESS IN REGISTERING INTO THE SERVICE; AND (II) IF YOU ARE AN ADMIN (AS DEFINED BELOW).AS ELABORATED IN SECTION 2 BELOW, THERE ARE VARIOUS TYPES OF USERS FOR THE SERVICE, THUS, EXCEPT WHERE INDICATED OTHERWISE “YOU” SHALL REFER TO CUSTOMER AND ALL TYPES OF USERS. YOU ACKNOWLEDGE THAT THESE TERMS ARE BINDING, AND YOU AFFIRM AND SIGNIFY YOUR CONSENT TO THESE TERMS, BY EITHER: (I) CLICKING ON A BUTTON OR CHECKING A CHECKBOX FOR THE ACCEPTANCE OF THESE TERMS; OR (II) REGISTERING TO, USING OR ACCESSING THE SERVICE, SITES OR PROCEZO MOBILE APPLICATION, WHICHEVER IS EARLIER (THE “EFFECTIVE DATE”). IF YOU DO NOT AGREE TO COMPLY WITH, AND BE BOUND BY, THESE TERMS OR DO NOT HAVE AUTHORITY TO BIND YOUR EMPLOYER OR ANY OTHER ENTITY (AS APPLICABLE), PLEASE DO NOT ACCEPT THESE TERMS OR ACCESS OR USE THE SERVICE OR THE SITES OR PROCEZO MOBILE APPLICATION.</p>
                                </div>
                                <div className="textRow">
                                    <h3>Our Service</h3>
                                    <p>Our Service. The Procezo platform is a cloud-based visual work management tool that transforms the way teams work together, with the aim to build a culture of transparency, ownership and accountability, inclusive of any and all functionalities, application programming interface and tools offered as part of Procezo platform, offered online and via a mobile application (the “Service”). Specific Terms may apply to You or to some of the Service, such specific terms are incorporated herein by reference and form an integral part hereof.</p>
                                    <p>Modification or Discontinuation of the Service. We may add, modify or discontinue any feature, functionality or any other tool, within the Service and/or Sites, at our own discretion and without further notice, however, if we make any material adverse change in the core functionality of the Service, then we will notify you by posting an announcement on the Sites and/or via the Service or by sending you an email.</p>
                                    <p>No Contingency on Future Releases and Improvements. You hereby acknowledge that your purchase of the Service and/or Third Party Services (as defined below) hereunder are not contingent on the delivery by us of any future release of any functionality or feature, including without limitation, the continuance of: (i) a certain Service beyond its current Subscription Term; or (ii) Third Party Services or dependent on any public comments we make, orally or in writing, regarding any future functionality or feature.</p>
                                    <p>Ability to Accept Terms. If you, access and use the Sites and/or the Service, you represent and warrant that you are at least 16 years old. The Sites and/or Service are only intended for individuals aged sixteen (16) years or older. We reserve the right to request proof of age at any stage so that we can verify compliance with this paragraph.</p>
                                </div>
                                <div className="textRow">
                                    <h3>Account Registration and Administration</h3>
                                    <p>Account Registration. To register to the Service for the first time, you shall create an account with the Service. By creating an account (“Account”) and registering to the Service you become, either individually or on behalf of your employer or any entity, on behalf of whom you created the Account, a Procezo customer (the “Customer”). The first user of the Account is automatically assigned as the Account administrator (the “Admin”).</p>
                                    <p>Your Registration Information. When creating an Account or when you are added into an Account and creating your user profile (the “User Profile”), you : (i) agree to provide us with accurate, complete, and current registration information about yourself; (ii) acknowledge that it is your responsibility to ensure that your password remains confidential and secure; (iii) agree that you are fully responsible for all activities that occur under your User Profile and password, including any integration or any other use of third party products or services (and associated disclosure of data) in connection with the Service; and (iv) undertake to promptly notify us in writing if you become aware of any unauthorized access or use of your Account or User Profile and/or any breach of these Terms. We may assume that any communications we receive under your User Profile have been made by you. Customer will be solely responsible and liable for any losses, damages, liability and expenses incurred by us or a third party, due to any unauthorized usage of the Account by either you or any other User or third party on your behalf.</p>
                                    <p>User Verification. You understand and agree that we may require you to provide information that may be used to confirm your identity and help ensure the security of your Account and/or User Profile. In the event that you or the Admin lose access to an Account or otherwise request information about an Account, we reserve the right to request from you or such Admin (as the case may be) any verification we deem necessary before restoring access to or providing information about such Account.</p>
                                    <p>Ability to Accept Terms. If you, access and use the Sites and/or the Service, you represent and warrant that you are at least 16 years old. The Sites and/or Service are only intended for individuals aged sixteen (16) years or older. We reserve the right to request proof of age at any stage so that we can verify compliance with this paragraph.</p>
                                    <p>Account Admins. The Admin(s) of an Account are, severally and jointly, deemed as the authorized representatives of the Customer, and any decision or action made by any Admin, is deemed as a decision or action of Customer. An Admin may assign or add other members of the Account as Admins, which possess important privileges and controls over the use of the Service and the Account, including, without limitation: (i) control your (and other Users) use of the Account; (ii) purchase, upgrade or downgrade the Service; (ii) create, monitor or modify Users’ actions and permissions; (iii) manage the access to, control, remove, share posts or otherwise change, all or part of the Customer Data (as defined below); and (iv) integrate or disable integration with Third Party Services. You also acknowledge that your Account can become managed by a representative of the entity that owns or controls the email address domain with which your Account was created or registered. Admin rights are further elaborated in our Help Center.</p>
                                    <p>Other Users. There are several types of Account users, such as guests, viewers and team members, all of whom are defined within the Service and referred to herein as “Authorized Users”, and collectively with the Admin, the “Users”. The features and functionalities available to the Users are determined by the respective subscription plan governing such Account, and the privileges of each such Authorized User are assigned and determined by the Account Admin(s). For more information on the rights, permissions and definition of each of the various types of Authorized Users, visit this Article in our Help Center.</p>
                                    <p>Responsibility for Authorized Users. Customer is solely liable and responsible for understanding the settings, privileges and controls for the Service and for controlling whom Customer permits to become a User and what are the settings and privileges for such User, including without limitation, the right for a User to invite other Users (either paid or unpaid), the right to incur charges on the Account, the right to access, modify or share boards, etc. Customer is responsible for the activities of all of its Users, including Order Forms they may place and how Users use the Customer Data, even if those Users are not from Customer’s organization or domain. Further, Customer acknowledges that any action taken by a User of Customer’s Account, is deemed by us as an authorized action by Customer, hence Customer shall have no claim in this regard.</p>
                                </div>
                                <div className="textRow">
                                    <h3>Your Customer Data</h3>
                                    <p>Customer Data. Customer Data is any data, file attachments, text, images, reports, personal information, or any other content, that is uploaded or submitted, transmitted or otherwise made available, to or through the Service by you or any User and is processed by us on Customer’s behalf (the “Customer Data”). For the avoidance of doubt, Anonymous Information (as defined below) is not regarded as Customer Data. Customer retains all right, title, interest and control, in and to the Customer Data, in the form submitted to the Service. Subject to these Terms, Customer grants us a worldwide, royalty-free, limited license to access, use, process, copy, distribute, perform, export, and display the Customer Data, and solely to the extent that reformatting Customer Data for display in the Service constitutes a modification or derivative work, the foregoing license also includes the right to make modifications and derivative works. The afore-mentioned license is hereby granted solely: (i) to maintain and provide you the Service; (ii) to prevent or address technical or security issues and resolve support requests; (iii) to investigate when we have a good faith belief, or have received a complaint alleging, that such Customer Data is in violation of these Terms; (iv) to comply with a valid legal subpoena, request, or other lawful process; and (v) as expressly permitted in writing by you.</p>
                                    <p>Responsibility for Customer Data Compliance. You represent and warrant that: (i) you have or have obtained all rights, licenses, consents, permissions, power and/or authority, necessary to grant the rights granted herein, for any Customer Data that you submit, post or display on or through the Service; (ii) the Customer Data is in compliance with, and subject to, our Acceptable Use Policy; and (iii) the Customer Data you submit, your use of such Customer Data, and our use of such Customer Data, as set forth in these Terms, do not and shall not (a) infringe or violate any patents, copyrights, trademarks or other intellectual property, proprietary or privacy, data protection or publicity rights of any third party; (b) violate any applicable local, state, federal and international laws, regulations and conventions, including those related to data privacy and data transfer and exportation (the “Laws”); (c) violate any of your or third party’s policies and terms governing the Customer Data. Other than our security and data protection obligations expressly set forth in Section 6, we assume no responsibility or liability for Customer Data, and you shall be solely responsible for Customer Data and the consequences of using, disclosing, storing, or transmitting it. It is hereby clarified that Procezo shall not monitor and/or moderate the Customer Data and there shall be no claim against Procezo of not acting so.</p>
                                    <p>No Sensitive Data. You shall not submit to the Service any data that is protected under a special legislation and requires a unique treatment, including, without limitations, (i) categories of data enumerated in European Union Regulation 2016/679, Article 9(1) or any similar legislation or regulation in other jurisdiction; (ii) any protected health information subject to the Health Insurance Portability and Accountability Act (“HIPAA”), as amended and supplemented, or any similar legislation in other jurisdiction, unless Customer and Procezo separately enter into a HIPAA Business Associate Agreement; and (iii) credit, debit or other payment card data subject to PCI DSS or any other credit card schemes.</p>
                                    <p>Ability to Accept Terms. If you, access and use the Sites and/or the Service, you represent and warrant that you are at least 16 years old. The Sites and/or Service are only intended for individuals aged sixteen (16) years or older. We reserve the right to request proof of age at any stage so that we can verify compliance with this paragraph.</p>
                                    <p></p>
                                    <p></p>
                                </div>
                                <div className="textRow">
                                    <h3>Public User Submissions</h3>
                                    <p>Public User Submissions. The Sites may have certain features that allow you to submit comments,information, and other materials publicly (collectively, “Public User Submissions”) and share such Public User Submissions with other Users, or the public. By submitting Public User Submissions through the Sites, you grant us a license to access, use, copy, reproduce, process, adapt, publish, transmit, host, and display that Public User Submissions for any purpose, business, including without limitation, for publicizing and promoting Procezo, the Service and/or the Sites and for any other lawful purpose, in any media format (e.g. in-print, websites. electronically, broadcast), and you hereby waive, or to the extent legally prohibited, assign to Procezo, any moral rights in your Public User Submissions.</p>
                                    <p>Responsibility for Public User Submissions. You acknowledge and agree that: (i) you have or have obtained all rights, licenses, consents, permissions, power and/or authority, necessary to grant the rights granted herein, for any Public User Submissions that you submit, post or display on or through the Service; (ii) we do not control, and are not responsible for, other content and/or submissions, posted on our Sites and/or Service by others; (iii) by using the Service and/or Sites, you may be exposed to content and/or submissions by other users or site visitors that is offensive, indecent, inaccurate, misleading, or otherwise unlawful; (iv) any Public User Submissions are submitted in accordance with, and subject to our Acceptable Use Policy.</p>
                                </div>
                                <div className="textRow">
                                    <h3>Intellectual Property Rights; License</h3>
                                    <p>Our Intellectual Property. The Service and Sites, inclusive of materials, such as software, application programming interface, design, text, editorial materials, informational text, photographs, illustrations, audio clips, video clips, artwork and other graphic materials, and names, logos, trademarks and services marks (excluding Customer Data), any and all related or underlying technology and any modifications, enhancements or derivative works of the foregoing (collectively, “ProcezoMaterials”), are the property of Procezo and its licensors, and may be protected by applicable copyright or other intellectual property laws and treaties. As between you and Procezo, Procezo retains all right, title and interest, including all intellectual property rights, in and to the Procezo Materials.</p>
                                    <p>Customer Reference. Customer acknowledges and accepts that Procezo has the right to use Customer’s name and logo to identify Customer as a customer of Procezo or User of the Service, on Procezo’s website, marketing materials or otherwise by public announcements. Customer may revoke such right, at any time, by contacting privacy@ibism.com.</p>
                                    <p>Your Access and Use Rights. Subject to the terms and conditions of these Terms, and your compliance thereof, and specifically in strict compliance with our Acceptable Use Policy, we grant you a limited, worldwide, non-exclusive, non-transferable right to access and use the Service and Sites, during the applicable Subscription Term, solely for Customer’s internal purposes.</p>
                                    <p>Use Restrictions. Except as expressly permitted in these Terms, you may not, and shall not allow an Authorized User or any third party to: (i) give, sell, rent, lease, timeshare, sublicense, disclose, publish, assign, market, resell, display, transmit, broadcast, transfer or distribute any portion of the Service or the Sites to any third party, including, but not limited to your affiliates, or use the Service in any service bureau arrangement; (ii) circumvent, disable or otherwise interfere with security-related features of the Sites or Service or features that prevent or restrict use or copying of any content or that enforce limitations on use of the Service or Sites; (iii) reverse engineer, decompile or disassemble, decrypt or, attempt to derive the source code of, the Service or Sites, or any components thereof; (iv) copy, modify, translate, patch, improve, alter, change or create any derivative works of the Service or Sites, or any part thereof; (v) take any action that imposes or may impose (at Procezo's sole discretion) an unreasonable or disproportionately large load on the Procezo infrastructure or infrastructure which supports the Sites or Service; (vi) interfere or attempt to interfere with the integrity or proper working of the Service or Sites, or any related activities; (vii) remove, deface, obscure, or alter Procezo's or any third party's identification, attribution or copyright notices, trademarks, or other proprietary rights affixed to or provided as part of the Service or Sites, or use or display logos of the Service or Sites without Procezo’s prior written approval; (viii) use the Service or Sites for competitive purposes, including to develop or enhance a competing service or product; or (ix) encourage or assist any third party (including other Authorized Users) to do any of the foregoing.</p>
                                    <p>Feedback. As a User of the Service and/or Sites, you may provide suggestions, comments, feature requests or other feedback to any of Procezo Materials, the Procezo Service, the API (in case you are the Admin) and/or the Sites (“Feedback”). Such Feedback is deemed an integral part of Procezo Materials, and as such, it is the sole property of Procezo without restrictions or limitations on use of any kind. Procezo may either implement or reject such Feedback, without any restriction or obligation of any kind. You (i) represent and warrant that such Feedback is accurate, complete, and does not infringe on any third party rights; (ii) irrevocably assign to Procezo any right, title and interest you may have in such Feedback; and (iii) explicitly and irrevocably waive any and all claims relating to any past, present or future moral rights, artists’ rights, or any other similar rights, worldwide, in or to such Feedback.</p>
                                    <p>API Use. We may offer an application programming interface that provides additional ways to access and use the Service ("API"). Such API is considered a part of the Service, and its use is subject to all these Terms. Without derogating from Sections 5.1 through 5.4 hereof, you may only access and use our API for Customer’s internal business purposes, in order to create interoperability and integration between the Service and other products, services or systems you and/or Customer use internally. When using the API you should follow our relevant developer guidelines. We reserve the right at any time to modify or discontinue, temporarily or permanently, your and/or Customer’s access to the API (or any part of it) with or without notice. The API is subject to changes and modifications, and you are solely responsible to ensure that your use of the API is compatible with the current version.</p>
                                </div>
                                <div className="textRow">
                                    <h3>Privacy and Security</h3>
                                    <p>Security. Procezo implements reasonable security measures and procedures to assist in protecting your Customer Data. You can learn more on our security measures and procedures on our Security Page, as updated from time to time.</p>
                                    <p>Privacy Policy. As a part of accessing or using the Service and the Sites, we may collect, access, use and share certain Personal Data (as defined in the Privacy Policy) from, and/or about, you. Please read our Privacy Policy, which is incorporated herein by reference, for a description of such data collection and use practices.</p>
                                    <p>Data Processing Agreement (“DPA”). By using the Service, Customer also accepts our Data Processing Agreement, which governs the Processing of Personal Data (as both terms are defined in the DPA) on Customer’s behalf, where such Personal Data is subject to the General Data Protection Regulation 2016/679 (the “GDPR”).</p>
                                    <p>Anonymous Information. Notwithstanding any other provision of these Terms, we may collect, use and publish Anonymous Information (defined below) relating to your use of the Service and/or Sites, and disclose it for the purpose of providing, improving and publicizing our products and services, including the Sites and Service, and for other business purposes. “Anonymous Information” means information which does not enable identification of an individual, such as aggregated and analytics information. Procezo owns all Anonymous Information collected or obtained by Procezo.</p>
                                </div>
                                <div className="textRow">
                                    <h3>Third Party Services; Links</h3>
                                    <p>Third Party Services. The Service enables you to engage and procure certain third party services, products, apps and tools in connection with the Service, including, without limitation, third party applications and widgets offered via our integrations offering or which you decide to connect through our API, as part of the Service (collectively, “Third Party Services”).</p>
                                    <p>Independent Relationship. You acknowledge and agree that regardless of the manner in which such Third Party Services may be offered to you, we merely act as an intermediary platform between you and such Third Party Services, and we do not, in any way, endorse any such Third Party Services, or shall be in any way responsible or liable with respect to any such Third Party Services. Your relationship with such Third Party Services and any terms governing your payment for, and use of, such Third Party Services, including without limitation, the collection, processing and use of your data by such Third Party Services, are subject to a separate contractual arrangement between you and the provider of a Third Party Service (the “Third Party Agreement”). We are not a party to, or responsible, in any manner, for the compliance by you or by the provider of the Third Party Service with the Third Party greement.</p>
                                    <p>Integration with a Third Party Service and your Customer Data. Through the Service you and any other Authorized User within the Account, may enable an integration of your Account, including, boards within your Account (or a portion thereof), with Third Party Services, which will allow an exchange, transmission, modification or removal of data between us and the Third Party Service, including without limitation, the Customer Data, the scope of which is determined by the applicable actions set by such integration. You hereby acknowledge that any access, collection, transmission, processing, storage or any other use of data, including the Customer Data, by a Third Party Service, is governed by the Third Party Agreement, including any applicable privacy policy, and Procezo is not responsible for any access, collection, transmission, processing, storage or any other use of data, including the Customer Data, by the Third Party Service or for such Third Party Service privacy and security actions, inactions or general practices. By integrating and/or using the Third Party Services, you acknowledge and agree that: (a) you are solely responsible for your compliance with applicable privacy restrictions, laws and regulations, including your use of the Third Party Service and other data activities you may conduct or may permit third parties, including the Third Party Service, to conduct; (b) the activities and use of the data by you and any other Users within the Account, may result in a modification and/or removal of data, either in the Account (i.e. Customer Data) and in the integrated Third Party Service. We shall have no obligation of any kind, for any such modification and/or removal of data, either in the Account with us and/or the integrated Third Party Service.</p>
                                    <p>Use Conditions and Limitations. Both Procezo and a Third Party Service may impose, each at its sole discretion, additional conditions or limitations on your access and use of certain Third Party Services, including without limitation, imposing a limited quota on the number of actions or other uses (as the case may be). Such additional conditions or limitations shall be indicated wherever relevant within the Service or the Third Party Service or otherwise notified to you or to any other relevant User of the Account.</p>
                                    <p>Payment for Third Party Services. Third Party Services may be offered free of charge or for a certain fee, either charged directly by the Third Party Service or by Procezo. Wherever the Third Party Service requires a payment, it shall be indicated next to the offering of the Third Party Service, unless such price is included within the Subscription Plan (as defined below) for the Service. Whenever Procezo charges Customer on behalf of itself and not as an agent on behalf of the Third Party Service, the payment terms, including the payment of fees, renewal and refund policy, are governed by Sections 8 and 9 herein. Whenever Procezo charges Customer on behalf of the Third Party Services, then Customer acknowledges that Procezo serves only as an intermediary role in facilitating or collecting the applicable fees and taxes from Customer, for the Third Party Service, thus all payment related issues, including the payment of fees, renewal and refund policy, are governed by the Third Party Agreement.</p>
                                    <p>Change of Fees. Customer acknowledges that Procezo and any Third Party Service, may change the fees for the Third Party Service from time to time, including imposing a new charge on a Third Party Service that was provided for free.</p>
                                    <p>Discontinuation of a Third Party Service. Each of Procezo and the Third Party Service reserves the right to discontinue the use or suspend the availability of any Third Party Service, for any reason and with no obligation to provide any explanation or notice. Such discontinuation may result in the inability to utilize certain features and actions of the Third Party Service along with our Service.</p>
                                    <p>Links. The Sites, Service and/or any Third Party Services may contain links to third party websites that are not owned or controlled by us (the “Links”). You acknowledge that we have no control over, and assume no responsibility for the content, privacy policies, or practices of, any third party websites. You: (i) are solely responsible and liable for your use of and linking to third party websites and any content that you may send or post to a third-party website; and (ii) expressly release us from any and all liability arising from your, and in case of a Customer, all Users’, use of any third party website. Accordingly, we encourage you to read the terms and conditions and privacy policy of each third party website that you may choose to visit.</p>
                                    <p>Limitations of Liability. PROCEZO BEARS NO RESPONSIBILITY AND/OR LIABILITY FOR ANY LINKS OR THIRD PARTY SERVICES, INCLUDING WITHOUT LIMITATION, SUCH THIRD PARTY SERVICE’S OPERABILITY OR INTEROPERABILITY WITH OUR SERVICE, SECURITY, ACCURACY, RELIABILITY, DATA PROTECTION AND PROCESSING PRACTICES AND THE QUALITY OF ITS OFFERINGS, AS WELL AS ANY ACTS OR OMMISSIONS BY THIRD PARTIES. BY ACCESSING AND/OR USING THE THIRD PARTY SERVICES, YOU ACKNOWLEDGE THAT YOUR ACCESS AND USE OF THE THIRD PARTY SERVICES ARE AT YOUR SOLE DISCRETION AND RISK, AND YOU ARE SOLELY RESPONSIBLE FOR ENSURING SUCH THIRD PARTY SERVICE’S OPERATION AND PRACTICES AND ITS RESPECTIVE THIRD PARTY AGREEMENT, MEET YOUR NEEDS.</p>
                                </div>
                                <div className="textRow">
                                    <h3>Subscription Term, Renewal and Fees Payment</h3>
                                    <p>Order Form. Our order form may be completed and placed in various ways, among which, an online form or in-product screens or any other mutually agreed upon offline form delivered by Customer or any of the other Users to Procezo, including via mail, email or any other electronic or physical delivery mechanism (the “Order Form”). Such Order Form will list, at the least, the Service ordered, subscription plan, term and the associated fees.</p>
                                    <p>Subscription Term. The Service is provided on a subscription basis for the term specified in your Order Form, in accordance with the respective subscription plan purchased under such Order Form (the “Subscription Term” and the “Subscription Plan”, respectively, and collectively the “Subscription”).
                                    </p>
                                    <p>Subscription Fees. In consideration for the provision of the Service (except for Trial Service), Customer shall pay us the applicable fees per the purchased Subscription, as set forth in the applicable Order Form (the “Subscription Fees”). Unless indicated otherwise, Subscription Fees are stated in US dollars. Customer hereby authorizes us, either directly or through our payment processing service, to charge such Subscription Fees via Customer’s selected payment method, upon due date. Unless expressly set forth herein, the Subscription Fees are non-cancelable and non-refundable. We reserve the right to change the Subscription Fees at any time, upon notice to Customer if such change may affect Customer’s existing subscriptions upon renewal. In the event of failure to collect the Fees owed by Customer, we may, at our sole discretion (but shall not be obligated to) retry to collect at a later time, and/or suspend or cancel the Account, without notice.</p>
                                    <p>Taxes. The Subscription Fees are exclusive of any and all taxes (including without limitation, value added tax, sales tax, use tax, excise, goods and services tax, etc.), levies, or duties, which may be imposed in respect of these Terms and the purchase or sale, of the Service hereunder (the “Taxes”), except for Taxes imposed on our income. If Customer is located in a jurisdiction which requires Customer to deduct or withhold Taxes or other amounts from any amounts due to us, please notify us, in writing, promptly and we shall join efforts to avoid any such Tax withholding, provided, however, that in any case, Customer shall bear the sole responsibility and liability to pay such Tax and such Tax should be deemed as being added on top of the Subscription Fees, payable by Customer.</p>
                                    <p>Subscription Upgrade. During the Subscription Term, Customer may upgrade its Subscription Plan by either: (i) adding Authorized Users; (ii) upgrading to a higher type of Subscription Plan; (iii) adding add-on features and functionalities; and/or (iv) upgrading to a longer Subscription Term (collectively, “Subscription Upgrades”). Some Subscription Upgrades or other changes may be considered as a new purchase, hence will restart the Subscription Term and some won’t, as indicated within the Service and/or the Order Form. Upon a Subscription Upgrade, Customer will be billed for the applicable increased amount of Subscription Fees, at our then-current rates (unless indicated otherwise in an Order Form), either: (1) prorated for the remainder of the then-current Subscription Term, or (2) whenever the Subscription Term is being restarted due to the Subscription Upgrade, then the Subscription Fees already paid by Customer will be reduced from the new upgraded Subscription Fees, and the difference shall be due and payable by Customer upon the date on which the Subscription Upgrade was made.</p>
                                    <p>Adding Users. Customer acknowledges that unless it disabled these options: (i) Users within the same email domain will be able to automatically join the Account; and (ii) Users within Customer’s Account may invite other persons to be added to the Account as Users (collectively, “Users Increase”). For further information on these options and how to disable them, visit our Help Center. Unless agreed otherwise in an Order Form, any changes to the number of Users within a certain Account, shall be billed on a prorated basis for the remainder of the then-current Subscription Term. We will bill Customer, either upon the Users Increase or at the end of the applicable month, as communicated to Customer.</p>
                                    <p>Excessive Usage. We shall have the right, including without limitation where we, at our sole discretion, believe that Customer and/or any of its Users, have misused the Service or otherwise use the Service in an excessive manner compared to the anticipated standard use (at our sole discretion), to offer the Subscription in different pricing and/or impose additional restrictions as for the upload, storage, download and use of the Service, including, without limitation, restrictions on Third Party Services, network traffic and bandwidth, size and/or length of content, quality and/or format of content, sources of content, volume of download time, etc.</p>
                                    <p>Billing. As part of registering, or submitting billing information, to the Service, Customer agrees to provide us with updated, accurate and complete billing information, and Customer authorizes us (either directly or through our affiliates, subsidiaries or other third parties) to charge, request and collect payment (or otherwise charge, refund or take any other billing actions) from Customer’s payment method or designated banking account, and to make any inquiries that we may consider necessary to validate Customer’s designated payment account or financial information, in order to ensure prompt payment, including for the purpose of receiving updated payment details from Customer’s credit card company or banking account (e.g., updated expiry date or card number as may be provided to us by Customer’s credit card company).</p>
                                    <p>Subscription Auto-Renewal. In order to ensure that Customer will not experience any interruption or loss of services, Customer’s Subscription includes an automatic renewal option by default, according to which, unless Customer disables the auto-renewal option or cancels its Subscription prior to its expiration, the Subscription will automatically renew upon the end of the then applicable Subscription Term, for a renewal period equal in time to the original Subscription Term (excluding extended periods) and, unless otherwise notified to Customer, at the same price (subject to applicable Tax changes and excluding any discount or other promotional offer provided for the first Subscription Term). Accordingly, unless either Customer or us cancel the Subscription prior to its expiration, we will attempt to automatically charge Customer the applicable Subscription Fees upon or immediately prior to the expiration of the then applicable Subscription Term. If Customer wishes to avoid such auto-renewal, Customer shall cancel its Subscription (or disable the auto-renewal option), prior to its expiration, at any time through the Account settings or by contacting our Customer Success team. Except as expressly set forth in these Terms, in case a Customer cancels its Subscription, during a Subscription Term, the Subscription will not renew for an additional period, but Customer will not be refunded or credited for any unused period within the Subscription Term.</p>
                                    <p>Discounts and Promotions. Unless expressly stated otherwise in a separate legally binding agreement, if Customer received a special discount or other promotional offer, Customer acknowledges that upon renewal of its Subscription, Procezo will renew such Subscription, at the full applicable Subscription Fee at the time of renewal.</p>
                                    <p>Credits. Any credits that may accrue to Customer’s Account, for any reason (the “Credits”), will expire and be of no further force and effect, upon the earlier of: (i) the expiration or termination of the applicable Subscription under the Account for which such Credits were given; or (ii) in case such Credits accrued for an Account with a Trial Subscription (as defined below) that was not upgraded to a Subscription Plan, then upon the lapse of 90 days of such Credits’ accrual. Unless specifically indicated otherwise, Credits may be used to pay for the Services only and not for any Third Party Service or other payment of whatsoever kind. Whenever fees are due for any Services, accrued Credits will be first reduced against the Subscription Fees and the remainder will be charged from Customer’s respective payment method. Credits shall have no monetary value (except for the purchase of Services under the limited terms specified herein) nor exchange value, and will not be transferable or refundable.</p>
                                    <p>Payment through Reseller. If Customer purchased a Service from a reseller or distributor authorized by us (“Reseller”), then to the extent there is any conflict between these Terms and the agreement entered between Customer and the respective Reseller, including any purchase order (“Reseller Agreement”), then, as between Customer and Procezo, these Terms shall prevail. Any rights granted to Customer and/or any of the other Users in such Reseller Agreement which are not contained in these Terms, apply only in connection with the Reseller. In that case, Customer must seek redress or realization or enforcement of such rights solely with the Reseller and not Procezo. For clarity, Customer’s and its Users’ access to the Service is subject to our receipt from Reseller of the payment of the applicable Fees paid by Customer to Reseller. Customer hereby acknowledges that at any time, at our discretion, the billing of the Subscription Fees may be assigned to us, such that Customer shall pay us directly the respective Subscription Fees.</p>
                                </div>
                                <div className="textRow">
                                    <h3>Refund Policy; Chargeback</h3>
                                    <p>Refund Policy. If Customer is not satisfied with its initial purchase of a Service, Customer may terminate such Service by providing us a written notice, within 30 days of having first ordered such Services (the “Refund Period”). In the event that Customer terminates such initial purchase of a Service, within the Refund Period, we will refund Customer the Subscription Fees paid in respect of such terminated Subscription, in the same currency we were originally paid (the “Refund”). The Refund is applicable only to the initial purchase of the Service by Customer and does not apply to any additional purchases, upgrades, modification or renewals of such Service. Please note that the Refund amount may be different than the amount Customer was charged due to currency changes and third party fees, such as wire transfer fees, and we shall not be responsible for any differences caused by change of currency exchange rates or fees that Customer was charged by third parties. After the Refund Period, the Subscription Fees are non-refundable and non-cancellable. To the extent permitted by law, if we find that a notice of cancellation has been given in bad faith or in an illegitimate attempt to avoid payment for Services actually received and enjoyed, we reserve our right to reject Customer’s Refund request.</p>
                                    <p>Non-Refundable Services. Certain Services may be non-refundable. In such event we will identify such Services as non-refundable, and Customer shall not be entitled, and we shall not be under any obligation, to terminate the Service and give a Refund.</p>
                                    <p>Chargeback. If, at any time, we record a decline, chargeback or other rejection of a charge of any due and payable Subscription Fees on Customer’s Account (“Chargeback”), this will be considered as a breach of Customer’s payment obligations hereunder, and Customer’s use of the Service may be disabled or terminated and such use of the Service will not resume until Customer re-subscribes for any such Service, and pay any applicable Subscription Fees in full, including any fees and expenses incurred by us and/or any Third Party Service for each Chargeback received (including handling and processing charges and fees incurred by the payment processor), without derogating from any other remedy that may be applicable to us under these Terms or applicable law.</p>
                                </div>
                                <div className="textRow">
                                    <h3>Trial Service; Pre-Released Services</h3>
                                    <p>Trial Service. We may offer, from time to time, part or all of our Services on a free, no-obligation trial version (“Trial Service”). The term of the Trial Service shall be as communicated to you, within the Service, in an Order Form, unless terminated earlier by either Customer or us, for any reason or for no reason. We reserve the right to modify, cancel and/or limit this Trial Service at any time and without liability or explanation to you. In respect of a Trial Service that is a trial version of the Subscription Plan (the “Trial Subscription”), upon termination of the Trial Subscription, we may change the Account web address at any time without any prior written notice.</p>
                                    <p>Pre-Released Services. Note that we may offer, from time to time, certain Services in an Alpha or Beta versions (the “Pre-Released Services”) and we use best endeavors to identify such Pre-Released Services as such. Pre-Released Services are Services that are still under development, and as such they may be inoperable or incomplete, and may contain bugs, suffer disruptions and/or not operate as intended and designated, more than usual.</p>
                                    <p>Governing Terms of Trial Service and Pre-Released Services. The Trial Service and Pre-Released Services are governed by these Terms, provided that notwithstanding anything in these Terms or elsewhere to the contrary, in respect of Trial Service and Pre-Released Services (i) such services are licensed hereunder on as “As-Is”, “With All Faults” “As Available” basis, with no warranties, express or implied, of any kind; (ii) the indemnity undertaking by us set forth in Section 16.2 herein shall not apply; and (iii) IN NO EVENT SHALL THE TOTAL AGGREGATE LIABILITY OF PROCEZO, ITSAFFILIATES OR ITS THIRD PARTY SERVICE PROVIDERS, UNDER, OR OTHERWISE IN CONNECTION WITH, THESE TERMS (INCLUDING THE SITES, THE SERVICE AND THE THIRD PARTY SERVICES), EXCEED US$100. We make no promises that any Trial Service and/or Pre-Released Services will be made available to you and/or generally available.</p>
                                </div>
                                <div className="textRow">
                                    <h3>Term and Termination; Suspension</h3>
                                    <p>Term. These Terms are in full force and effect, commencing upon the Effective Date, until the end of the Service underlying the Account, either paid or unpaid, unless terminated otherwise in accordance with these Terms.</p>
                                    <p>Termination for Cause. Either Customer or us may terminate the Service and these Terms, upon written notice, in case that (a) the other party is in material breach of these Terms and to the extent, curable, fails to cure such breach, within a reasonable cure period, which shall not be less than 10 days following a written notice from by the non-breaching party; or (b) ceases its business operations or becomes subject to insolvency proceedings and the proceedings are not dismissed within 45 days.</p>
                                    <p>Termination by Customer. Customer may terminate its Subscription to the Service by cancelling the Service and/or deleting the Account, whereby such termination shall not derogate from Customer’s obligation to pay applicable Subscription Fees except where such termination is made within the Refund Period. In accordance with Section 9 above, unless mutually agreed otherwise by Customer and us in a written instrument, the effective date of such termination will take effect at the end of the then-current Subscription Term, and Customer’s obligation to pay the Subscription Fees throughout the end of such Subscription Term shall remain in full force and effect, and Customer shall not be entitled to a refund for any pre-paid Subscription Fees.</p>
                                    <p>Effect of Termination of Service. Upon termination or expiration of these Terms, Customer’s Subscription and all rights granted to you hereunder shall terminate, and we may change the Account’s web address. It is Customer’s sole liability to export the Customer Data prior to such termination or expiration. In the event that Customer did not delete the Customer Data from the Account, we may continue to store and host it until either Customer or we, at our sole discretion, delete such Customer Data, and during such period, Customer shall still be able to make a limited use of the Service in order to export the Customer Data (the “Read-Only Mode”), but note that we are not under any obligation to maintain the Read-Only Mode period, hence such period may be terminated by us, at any time, with or without notice to Customer, and subsequently, the Customer Data will be deleted. Customer acknowledges the foregoing and its sole responsibility to export and/or delete the Customer Data prior to the termination or expiration of these Terms, and therefore we shall not have any liability either to Customer, nor to any User or third party, in connection thereto. Unless expressly indicated herein otherwise, the termination or expiration of these Terms shall not relieve Customer from its obligation to pay due Subscription Fees.</p>
                                    <p>Survival. Section 2.6 (Responsibility for Authorized Users), 3 (Customer Data), 6 (Privacy and Security), 7 (Third Party Services), 8 (Subscription Term, Renewal and Fees Payment) in respect of unpaid Subscription Fees, 10.3 (Governing Terms of Trial Services and Pre-Released Services), 11 (Term and Termination; Suspension), 12 (Confidentiality), 13 (Warranty Disclaimer), 14 (Limitations of Liability), 16 (Indemnification), 21 (Governing Law and Jurisdiction; Class Action Waiver and Arbitration) and 22 (General Provisions), shall survive the termination or expiration of these Terms, and continue to be in force and effect in accordance with their applicable terms.</p>
                                    <p>Suspension. Without derogating from our termination rights above, we may decide to temporarily suspend the Account and/or a User Profile (including any access thereto) and/or our Service, in the following events: (i) we believe, at our sole discretion, that you or any third party, are using the Service in a manner that may impose a security risk, may cause harm to us or any third party, and/or may raise any liability for us or any third party; (ii) we believe, at our sole discretion, that you or any third party, are using the Service in breach of these Terms or applicable Law; (iii) Customer’s payment obligations, in accordance with these Terms, are or are likely to become, overdue; or (iv) Customer’s or any of its Users’ breach of the Acceptable Use Policy. The afore-mentioned suspension rights are in addition to any remedies that may be available to us in accordance with these Terms and/or applicable Law.</p>
                                </div>
                                <div className="textRow">
                                    <h3>Confidentiality</h3>
                                    <p>Confidential Information. In connection with these Terms and the Service (including the evaluation thereof), each party (“Disclosing Party”) may disclose non-public business, product, technology and marketing information, including without limitation, customers lists and information, know-how, softwareand any other non-public information that is either identified as such or should reasonably be understood to be confidential given the nature of the information and the circumstances of disclosure, whether disclosed prior or after the Effective Date (the “Confidential Information”) to the other party (“ReceivingParty”). For the avoidance of doubt, (i) Customer Data is regarded as Customer’s Confidential Information, and (ii) our Site, Service, Trial Service and/or Pre-Released Services, inclusive of their underlying technology, and their respective performance information, as well as any data, reports and materials we provided to you in connection with your evaluation or use of the Service, are regarded as our Confidential Information. Confidential Information does not include information that (a) is or becomes generally available to the public without breach of any obligation owed to the Disclosing Party; (b) was known to the Receiving Party prior to its disclosure by the Disclosing Party without breach of any obligation owed to the Disclosing Party; (c) is received from a third party without breach of any obligation owed to the Disclosing Party; or (d) was independently developed by the Receiving Party without any use or reference to the Confidential Information.</p>
                                    <p>Confidentiality Undertakings by the Receiving Party. The Receiving Party will (i) take at least reasonable measures to prevent the unauthorized disclosure or use of Confidential Information, and limit access to those employees, affiliates, service providers and agents, on a need to know basis and who are bound by confidentiality obligations at least as restrictive as those contained herein; and (ii) not use or disclose any Confidential Information to any third party, except as part of its performance under these Terms and as required to be disclosed to legal or financial advisors to the Receiving Party or in connection with a due diligence process that the Receiving Party is undergoing, provided that any such disclosure shall be governed by confidentiality obligations at least as restrictive as those contained herein.</p>
                                    <p>Compelled Disclosure. Notwithstanding the above, Confidential Information may be disclosed pursuant to the order or requirement of a court, administrative agency or other governmental body; provided, however, that to the extent legally permissible, the Receiving Party shall make best efforts to provide prompt written notice of such court order or requirement to the Disclosing Party to enable the Disclosing Party to seek a protective order or otherwise prevent or restrict such disclosure.</p>
                                </div>
                                <div className="textRow">
                                    <h3>Confidentiality</h3>
                                    <p>NOTWITHSTANDING ANYTHING IN THESE TERMS OR ELSEWERE TO THE CONTRARY AND TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW:</p>
                                    <p>EXCEPT AS EXPRESSLY SET FORTH HEREIN, THE SITES AND THE SERVICE ARE PROVIDED ON AN "AS IS", “WITH ALL FAULTS” AND "AS AVAILABLE" BASIS, AND WITHOUT WARRANTIES OF ANY KIND. WE AND OUR AFFILIATES, SUBCONTRACTORS, AGENTS AND VENDORS (INCLUDING, THE THIRD PARTY SERVICE PROVIDERS, HEREBY DISCLAIM ANY AND ALL REPRESENTATIONS AND WARRANTIES OF ANY KIND, INCLUDING WITHOUT LIMITATION, WARRANTIES AND/OR REPRESENTATIONS OF MERCHANTABILITY, FUNCTIONALITY, TITLE, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, WHETHER EXPRESS, IMPLIED OR STATUTORY.</p>
                                    <p>WE AND OUR VENDORS DO NOT WARRANT, AND EXPRESSLY DISCLAIM ANY WARRANTY OR REPRESENTATION THAT THE SERVICE AND SITES, INCLUDING THE ACCESS THERETO AND USE THEREOF, WILL BE UNINTERRUPTED, TIMELY, SECURED, ERROR FREE, THAT DATA WON’T BE LOST, THAT DEFECTS WILL BE CORRECTED, OR THAT THE SITES AND/OR SERVICE ARE FREE FROM VIRUSES OR OTHER HARMFUL CODE. WE AND OUR VENDORS FURTHER DISCLAIM ANY AND ALL LIABILITY OR RESPONSIBILITY FOR ANY DELAYS, FAILURES, INTERCEPTION, ALTERATION, LOSS, OR OTHER DAMAGES THAT YOU AND/OR YOUR DATA (INCLUDING CUSTOMER DATA) MAY SUFFER, THAT ARE BEYOND OUR CONTROL.</p>
                                    <p>EXCEPT AS EXPRESSLY SET FORTH HEREIN, WE DO NOT WARRANT, AND EXPRESSLY DISCLAIM ANY WARRANTY OR REPRESENTATION (I) THAT OUR SERVICE (OR ANY PORTION THEREOF) IS COMPLETE, ACCURATE, OF ANY CERTAIN QUALITY, RELIABLE, SUITABLE FOR, OR COMPATIBLE WITH, ANY OF YOUR CONTEMPLATED ACTIVITIES, DEVICES, OPERATING SYSTEMS, BROWSERS, SOFTWARE OR TOOLS (OR THAT IT WILL REMAIN AS SUCH AT ANY TIME), OR COMPLY WITH ANY LAWS APPLICABLE TO YOU; AND/OR (II) REGARDING ANY CONTENT, INFORMATION, REPORTS OR RESULTS THAT YOU OBTAIN THROUGH THE SERVICE AND/OR THE SITES.</p>
                                </div>
                                <div className="textRow">
                                    <h3>Limitation of Liability</h3>
                                    <p>NOTWITHSTANDING ANYTHING IN THESE TERMS OR ELSEWERE TO THE CONTRARY AND TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW:</p>
                                    <p>IN NO EVENT SHALL EITHER PARTY HERE TO AND ITS AFFILIATES, SUB CONTRACTORS, AGENTS AND VENDORS (INCLUDING, THE THIRD PARTY SERVICE PROVIDERS), BE LIABLE UNDER, OR OTHERWISE IN CONNECTION WITH THESE TERMS FOR (I) ANY INDIRECT, EXEMPLARY, SPECIAL, CONSEQUENTIAL, INCIDENTAL OR PUNITIVE DAMAGES; (II) ANY LOSS OF PROFITS, COSTS, ANTICIPATED SAVINGS; (III) ANY LOSS OF, OR DAMAGE TO DATA, USE, BUSINESS, REPUTATION, REVENUE OR GOODWILL; AND/OR (IV) THE FAILURE OF SECURITY MEASURES AND PROTECTIONS, WHETHER IN CONTRACT, TORT OR UNDER ANY OTHER THEORY OF LIABILITY OR OTHERWISE, AND WHETHER OR NOT SUCH PARTY HAS BEEN ADVISED OF THEPOSSIBILITY OF SUCH DAMAGES IN ADVANCE, AND EVEN IF A REMEDY FAILS OF ITS ESSENTIAL PURPOSE.</p>
                                    <p>EXCEPT FOR THE INDEMNITY OBLIGATIONS OF EITHER PARTY UNDER SECTION 16 (INDEMNIFICATION) HEREIN, YOUR PAYMENT OBLIGATIONS HERE UNDER OR BREACH OF OUR ACCEPTABLE USE POLICY BY EITHER YOU OR IN CASE OF A CUSTOMER, ANY OF THE USERS UNDERLYING ITS ACCOUNT, IN NO EVENT SHALL THE TOTAL AGGREGATE LIABILITY OF EITHER PARTY, ITS AFFILIATES, SUBCONTRACTORS, AGENTS AND VENDORS (INCLUDING, THE ITS THIRD-PARTY SERVICE PROVIDERS), UNDER, OR OTHERWISE IN CONNECTION WITH, THESE TERMS (INCLUDING THE SITES AND THE SERVICE), EXCEED THE TOTAL AMOUNT OF FEES ACTUALLY PAID BY YOU (IF ANY) DURING THE 12 CONSECUTIVE MONTHS PRECEDING THE EVENT GIVING RISE TO SUCH LIABILITY. THIS LIMITATION OF LIABILITY IS CUMULATIVE AND NOT PER INCIDENT.</p>
                                </div>
                                <div className="textRow">
                                    <h3>Specific Laws; Reasonable Allocation of Risks</h3>
                                    <p>Specific Laws. Except as expressly stated in these Terms, we make no representations orwarranties that your use of the Service is appropriate in your jurisdiction. Other than as indicated herein, you are responsible for your compliance with any local and/or specific applicable Laws, as applicable to your use of the Service.</p>
                                    <p>Reasonable Allocation of Risks. You hereby acknowledge and confirm that the limitations of liability and warranty disclaimers contained in these Terms are agreed upon by you and us and we both find such limitations and allocation of risks to be commercially reasonable and suitable for our engagement hereunder, and both you and us have relied on these limitations and risk allocation in determining whether to enter these Terms.</p>
                                </div>
                                <div className="textRow">
                                    <h3>Indemnification</h3>
                                    <p>By Customer. Customer hereby agrees to indemnify, defend and hold harmless Procezo and its affiliates, officers, directors, employees and agents from and against any and all claims, damages, obligations, liabilities, losses, reasonable expenses or costs (collectively, “Losses”) incurred as a result of any third party claim arising from (i) Customer’s and/or any of its Users’, violation of these Terms or applicable Law; and/or (ii) Customer Data, including the use of Customer Data by Procezo and/or any of its subcontractors, infringes or violates, any third party’s rights, including, without limitation, intellectual property, privacy and/or publicity rights.</p>
                                    <p>By Procezo. Procezo hereby agrees to defend Customer, its affiliates, officers, directors, and employees, in and against any third party claim or demand against Customer, alleging that Customer’s authorized use of the Service infringes or constitutes misappropriation of any third party’s copyright, trademark or registered US patent (the “IP Claim”), and we will indemnify Customer and hold Customer harmless against any damages and costs finally awarded on such IP Claim by a court of competent jurisdiction or agreed to via settlement we agreed upon, including reasonable attorneys’ fees. Procezo’s indemnity obligations under this Section 16 shall not apply if: (i) the Service (or anyportion thereof) was modified by Customer or any of its Users or any third party, but solely to the extent the IP Claim would have been avoided by not doing such modification; (ii) if the Service is used in combination with any other service, device, software or products, including, without limitation, Third Party Services, but solely to the extent that such IP Claim would have been avoided without such combination; and/or (ii) any IP Claim arising or related to, the Customer Data or to any events giving rise to Customer’s indemnity obligations under Section 16.1 above. Without derogating from the foregoing defense and indemnification obligation, if Procezo believes that the Service, or any part thereof, may so infringe, then Procezo may in its sole discretion: (i) obtain (at no additional cost to you) the right to continue to use the Service; (ii) replace or modify the allegedly infringing part of the Service so that it becomes non-infringing while giving substantially equivalent performance; or (iii) if Procezo determines that the foregoing remedies are not reasonably available, then Procezo may require that use of the (allegedly) infringing Service (or part thereof) shall cease and in such an event, Customer shall receive a prorated refund of any Subscription Fees paid for the unused portion of the Subscription Term. THIS SECTION 16.2 STATES PROCEZO’S SOLE AND ENTIRE LIABILITY AND YOUR EXCLUSIVE REMEDY, FOR ANY INTELLECTUAL PROPERTY INFRINGEMENT OR MISAPPROPRIATION BY PROCEZO AND/OR ITS SERVICE AND UNDERLYING TECHNOLOGY.</p>
                                    <p>Indemnity Conditions. The defense and indemnification obligations of the indemnifying party under this Section 16 are subject to: (i) the indemnified party shall promptly provide a written notice of the claim for which an indemnification is being sought, provided that such indemnitee's failure to do so will not relieve the indemnifying party of its obligations under this Section 16, except to the extent the indemnifying party’s defense is materially prejudiced thereby; (ii) the indemnifying party being given immediate and exclusive control over the defense and/or settlement of the claim, provided, however that the indemnifying party shall not enter into any compromise or settlement of any such claim that that requires any monetary obligation or admission of liability or any unreasonable responsibility or liability by an indemnitee without the prior written consent of the affected indemnitee, which shall not be unreasonably withheld or delayed; and (iii) the indemnified party providing reasonable cooperation and assistance, at the indemnifying party’s expense, in the defense and/or settlement of such claim and not taking any action that prejudices the indemnifying party’s defense of, or response to, such claim.</p>
                                </div>
                                <div className="textRow">
                                    <h3>Third Party Components within Our Service</h3>
                                    <p>Our Service includes third party codes and libraries that are subject to third party open source license terms (the “Open Source Code” and the “Open Source Terms”, respectively). Some of such Open Source Terms determine that to the extent applicable to the respective Open Source Code licensed thereunder, such terms prevail over any conflicting license terms, including these Terms. We use our best endeavors to identify such Open Source Code, within our Service, hence we encourage Customer to familiarize itself with such Open Source Terms. Note that we use best efforts to use only Open Source Codes that does not impose any obligation or affect the Customer Data or related intellectual property (beyond what is stated in the Open Source Terms and herein), on an ordinary use of our Service that does not involve any modification, distribution or independent use of such Open Source Code. Notwithstanding anything to the contrary, we make no warranty or indemnity hereunder with respect to any Open Source Codes.</p>
                                </div>
                                <div className="textRow">
                                    <h3>Export Controls</h3>
                                    <p>The Service may be subject to Israeli, U.S. or foreign export controls, Laws and regulations (the “Export Controls”), and you acknowledge and confirm that: (i) you are not located or use, export, re-export or import the Service (or any portion thereof) in or to, any person, entity, organization, jurisdiction or otherwise, in violation of the Export Controls; (ii) Customer is solely responsible for complying with applicable Export Controls which may impose additional restrictions, prohibitions or requirements on the use, export, re-export or import of the Services and/or the Customer Data; and (iii) Customer Data is not controlled under the U.S. International Traffic in Arms Regulations or similar Laws in other jurisdictions, or otherwise requires any special permission or license, in respect of its use, import, export or re-export hereunder.</p>
                                </div>
                                <div className="textRow">
                                    <h3>Modifications</h3>
                                    <p>Occasionally we may make changes to these Terms for valid reasons, such as adding new functions or features to the Service, technical adjustments, typos or error fixing, for legal or regulatory reasons or for any other reasons as we deem necessary, at our sole discretion. When we make material changes to these Terms, we’ll provide Customer with notice as appropriate under the circumstances, e.g., by displaying a prominent notice within the Service or by sending Customer an email. Your continued use of the Service after the changes have been implemented will constitute your acceptance of the changes.</p>
                                </div>
                                <div className="textRow">
                                    <h3>Government Use</h3>
                                    <p>If Customer is part of a U.S. Government agency, department or otherwise, either federal, state or local (a “Government Customer”), then the terms of this Section 20 shall apply to Customer. Government Customer’s technical data and software rights related to the Service include only those rights customarily provided to the public as specified in these Terms. Government Customer hereby agrees that the Service qualifies as a “Commercial Computer Software” and “Commercial Computer Software Documentation”, within the meaning of 48 C.F.R. §12.212 or 48 C.F.R. §227.7202 to §227.7204. If a Government Customer has a need for rights not granted under the Terms, it must negotiate with us to determine if there are acceptable terms for granting those rights, and a mutually acceptable written addendum specifically granting those rights must be included in any applicable agreement. Any unpublished-rights are reserved under applicable copyright laws. Any provisions contained in these Terms that contradict any Law applicable to a Government Customer, shall be limited solely to the extent permitted under such applicable Law.</p>
                                </div>
                                <div className="textRow">
                                    <h3>Governing Law and Jurisdiction; Class Action Waiver and Mandatory Arbitration</h3>
                                    <p>Governing Law; Jurisdiction. These Terms and any action related thereto will be governed and interpreted by and under the laws of the State of Israel without giving effect to any conflicts of laws principles that require the application of the law of a different jurisdiction. Courts of competent jurisdiction located in Gurugram, India, shall have the sole and exclusive jurisdiction and venue over all controversies and claims arising out of, or relating to, these Terms. You and us mutually agree that the United Nations Convention on Contracts for the International Sale of Goods does not apply to these Terms. Notwithstanding the foregoing, Procezo reserves the right to seek injunctive relief in any court in any jurisdiction.</p>
                                    <p>Class Action Waiver. WHERE PERMITTED UNDER APPLICABLE LAW, YOU AND PROCEZO AGREE THAT EACH PARTY MAY BRING CLAIMS AGAINST THE OTHER PARTY ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE ACTION. Unless both you and Procezo mutually agree, no arbitrator or judge may consolidate more than one person’s claims or otherwise preside over any form of a representative or class proceeding.</p>
                                    <p><strong>Arbitration. To the extent permitted under applicable Law, you and Procezo hereby irrevocably agree to the following provisions:</strong></p>
                                    <p>Dispute resolution and Arbitration. Any dispute, claim, or controversy between you and us arising in connection with, or relating in any way to, these Terms (whether based in contract, tort, statute, fraud, misrepresentation, or any other legal theory, and whether the claims arise during or after the termination or expiration of these Terms) will be determined solely by mandatory binding arbitration. In arbitration there is no judge or jury and court review of an arbitration award is limited. However, an arbitrator can award on an individual basis the same damages and relief as a court (including injunctive and declaratory relief or statutory damages) and must follow the terms of these Terms as a court would.</p>
                                    <p>Exception. Notwithstanding clause 21.3.1 above, you and Procezo both agree that nothing herein will be deemed to waive, preclude, or otherwise limit either of our rights, at any time, to seek injunctive relief in a court of law. In addition to the above, notwithstanding clause 21.3.1 above, Procezo may file a suit in a court of law against you to address intellectual property infringement claims.</p>
                                    <p>Arbitration Process Rules. Either you or we may start arbitration proceedings. Any arbitration between you and us will be finally settled under the Rules of Arbitration of the International Chamber of Commerce (the “ICC”) then in force (the “ICC Rules”) by one arbitrator appointed in accordance with the ICC Rules. The arbitration will take place in Tel Aviv-Jaffa, and shall be conducted in the English language and unless otherwise required by a mandatory law of any jurisdiction, the law to be applied in any arbitration shall be the law of the State of Israel, without regard to choice or conflicts of law principles. The arbitration proceedings shall be conducted on an expedited basis and shall result in an award within no more than 60 days. The arbitration shall be conducted on a confidential basis. The award of the Arbitrator shall be final and binding on the parties. The arbitration award shall be enforceable in any court of competentjurisdiction. Any motion to enforce or vacate an arbitration award under this agreement shall be kept confidential to the maximum extent possible.</p>
                                    <p>Special Statute of Limitation. Any arbitration must be commenced by filing a demand for arbitration within 2 years after the date the party asserting the claim first knows or reasonably should know of the act, omission, or default giving rise to the claim; and there shall be no right to any remedy for any claim not asserted within that time period. If applicable law prohibits such limitation period for asserting claims, any claim must be asserted within the shortest time period permitted by applicable Law.</p>
                                    <p>Notice; Process. A party who intends to seek arbitration must first send a written notice of the dispute to the other, by certified mail or Federal Express (signature required), or in the event that we do not have a physical address on file for you, by electronic mail (“Dispute Notice”). The Dispute Notice must (i) describe the nature and basis of the claim or dispute; and (ii) set forth the specific relief sought. We agree to use good faith efforts to resolve the claim directly, but if we do not reach an agreement to do so within 30 days after the Dispute Notice is received, you or us may commence an arbitration proceeding. During the arbitration, the amount of any settlement offer made by you or us shall not be disclosed to the arbitrator until after the arbitrator makes a final decision and award, if any. Without derogating from the generality of the confidentiality protection under Section 21.3.3 above, all documents and information disclosed in the course of the arbitration shall be kept strictly confidential by the recipient and shall not be used by the recipient for any purpose other than for purposes of the arbitration or the enforcement of the arbitrator’s decision and award and shall not be disclosed except in confidence to persons who have a need to know for such purposes or as required by applicable Law. Except as required to enforce the arbitrator’s decision and award, neither you nor us shall make any public announcement or public comment or originate any publicity concerning thearbitration, including, but not limited to, the fact that the parties are in dispute, the existence of the arbitration, or any decision or award of the arbitrator.</p>
                                </div>
                                <div className="textRow">
                                    <h3>General Provisions</h3>
                                    <p>Translated Versions. These Terms were written in English, and translated into other languages for your convenience. If a translated (non-English) version of these Terms conflicts in any way with their English version, the provisions of the English version shall prevail. Force Majeure. Neither us nor you will be liable by reason of any failure or delay in the performance of its obligations on account of events beyond the reasonable control of a party, which may include denial-of-service attacks, interruption or failure of the Internet or any utility service, failures in third-party hosting services, strikes, shortages, riots, fires, acts of God, war, terrorism, and governmental action.</p>
                                    <p>Relationship of the Parties; No Third Party Beneficiaries. The parties are independent contractors.These Terms and the Service provided hereunder, do not create a partnership, franchise, joint venture, agency, fiduciary or employment relationship between the parties. There are no third party beneficiaries to these Terms.</p>
                                    <p>Notice. We shall use your contact details that we have in our records, in connection with providing you notices, subject to this Section 22.4. Our contact details for any notices are detailed below. You acknowledge notices that we provide you, in connection with these Terms and/or as otherwise related to the Service, shall be provided as follows: via the Service, including by posting on our Sites or posting in your account, text, in-app notification, e-mail, phone or first class, airmail, or overnight courier. You further acknowledge that an electronic notification satisfies any applicable legal notification requirements, including that such notification will be in writing. Any notice to you will be deemed given upon the earlier of: (i) receipt; or (ii) 24 hours of delivery. Notices to us shall be provided to Envigo Marketing Limited Ltd., attn: General Counsel, at privacy@ibism.com, or sent to Springhouse Co-Working LG 006, Grand Mall, Mehrauli-Gurgaon Rd, Gurugram, Haryana 122002, India</p>
                                    <p>Assignment. These Terms, and any and all rights and obligations hereunder, may not be transferred or assigned by you without our written approval, provided that you may assign these Terms to your successor entity or person, resulting from a merger, acquisition, or sale of all or substantially all of your assets or voting rights, except for an assignment to a competitor of Procezo, and provided that you provide us with prompt written notice of such assignment and the respective assignee agrees, in writing, to assume all of your obligations under these Terms. We may assign our rights and/or obligations hereunder and/or transfer ownership rights and title in the Service to a third party without your consent or prior notice to you. Subject to the foregoing conditions, these Terms shall bind and inure to the benefit of the parties, their respective successors, and permitted assigns. Any assignment not authorized under this Section 22.5 shall be null and void.</p>
                                    <p>Severability. These Terms shall be enforced to the fullest extent permitted under applicable Law.</p>
                                    <p>If any provision of these Terms is held by a court of competent jurisdiction to be contrary to law, the provision will be modified by the court and interpreted so as best to accomplish the objectives of the original provision to the fullest extent permitted by law, and the remaining provisions of these Terms will remain in effect.</p>
                                    <p>No Waiver. No failure or delay by either party in exercising any right under these Terms will constitute a waiver of that right. No waiver under these Terms will be effective unless made in writing and signed by an authorized representative of the party being deemed to have granted the waiver.</p>
                                    <p><strong>Last update: March 1, 2020</strong></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </WebBase>

                <Helmet>
                    <title>Procezo : Terms of Service</title>
                </Helmet>
            </>
        );
    }
}

export default TermsOfServiceContainer;
